from .task01 import *
from .task02 import *
from .task03 import *
from .task04 import *
from .task05 import *
from .task06 import *
from .task07 import *
from .task08 import *
from .task09 import *
from .task10 import *
from .task11 import *
from .task12 import *
from .task13 import *
from .task14 import *
from .task15 import *
from .task16 import *
from .task17 import *
from .task18 import *
from .task19 import *
from .task20 import *
from .task21 import *
from .task22 import *
from .task23 import *