from .task01 import *
from .task02 import *
from .task03 import *
from .task04 import *
from .task05 import *
from .task06 import *
from .task07 import *
from .task08 import *
from .task09 import *
from .task10 import *
from .task11 import *
from .task12 import *
from .task13 import *
from .task14 import *
from .task15 import *
from .task15_2 import *
from .zzz_old_task08 import *
from .zzz_old_task10 import *